Batat/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Batat.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Batat";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Batat/Controllers/SeedDatabaseController.cs
using System.Linq;
using System.Web.Mvc;
using Batat.Helpers.Extensions.DatabasePanel;
using Batat.Models.Database.DbContexts;
using Batat.Models.Helpers.DatabasePanel;
using Batat.Models.Helpers.ProductionPanel;
using Batat.SeedDatabase.Seeds;

namespace Batat.Controllers
{
    [AllowAnonymous]
    public class SeedDatabaseController : Controller
    {
        private ApplicationDataDbContext Context { get; } = ApplicationDataDbContext.Create();

        public ActionResult RecreateDatabase()
        {
            TempData["Message"] = SeedDatabaseHelper.DropAllTablesWithSqlQuery();

            
            var dbMigrationsConfiguration =
                new System.Data.Entity.Migrations.DbMigrationsConfiguration<ApplicationDataDbContext>
                {
                    AutomaticMigrationsEnabled = true,
                    AutomaticMigrationDataLossAllowed = true,
                    MigrationsDirectory = @"Migrations\ApplicationDataMigrations"
                };

            var dbMigrator = new System.Data.Entity.Migrations.DbMigrator(dbMigrationsConfiguration);
            dbMigrator.Update();
            

            SeedDatabase.Seeds.SeedDatabase.AddUsersAndRoles(Context);
            
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedDatabasePanel()
        {
            // Seed Groups
            if (!Context.Groups.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedGroups(Context);
            }
            if (!Context.OperationTypes.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedOperationTypes(Context);
            }
            if (!Context.MachineTypes.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedMachineTypes(Context);
            }

            // Seed Subjects i Contacts

            if (!Context.Subjects.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedSubjects(Context);
            }

            // Seed Orders, Produkty, Detale i Parametry
            if (!Context.Parameters.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedParameters(Context);
            }

            if (!Context.Parts.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedParts(Context);
            }

            if (!Context.Products.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedProducts(Context);
            }

            // Seed Technologies, Operations, Machines i Operatorzy
            if (!Context.Technologies.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedToolTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedTools(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedMaterialTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedMaterials(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedOperators(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedMachines(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedTechnologies(Context);
            }

            // Seed Fixed costs
            if (!Context.FixedCosts.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCostCategories(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCostTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCosts(Context);
            }

            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedOrderInstances()
        {
            if (!Context.OrderInstances.Any())
                SeedDatabase.Seeds.SeedDatabase.SeedOrderInstances(Context);

            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedTechnologyPicks()
        {
            if (!Context.ProductionTechnologyBundles.Any())
                new TechnologyPicksSeeder(Context).Seed();

            return RedirectToAction("Index", "Home", null);
        }
        public ActionResult SeedTroleys()
        {
            if (Context.Trolleys.All(a => a.MachineId == 0))
                new TroleySeeder(Context).Seed();
                
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult RemoveOrderInstances()
        {
            Context.ProductionTechnologies.RemoveRange(Context.ProductionTechnologies);
            Context.ProductionOperations.RemoveRange(Context.ProductionOperations);
            Context.ProductionTechnologyBundles.RemoveRange(Context.ProductionTechnologyBundles);
            Context.Boxes.RemoveRange(Context.Boxes);
            Context.Trolleys.RemoveRange(Context.Trolleys);
            Context.SaveChanges();

            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedGroups()
        {
            if (!Context.Groups.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedGroups(Context);
            }

            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedParameters()
        {
            if (!Context.Parameters.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedParameters(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedParts()
        {
            if (!Context.Parts.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedParts(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedProducts()
        {
            if (!Context.Products.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedProducts(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedSubjects()
        {
            if (!Context.Subjects.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedSubjects(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedOrders()
        {
            if (!Context.Orders.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedOrders(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedOperators()
        {
            if (!Context.Operators.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedOperators(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedMachines()
        {
            if (!Context.Machines.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedMachines(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedTools()
        {
            if (!Context.Tools.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedToolTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedTools(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedMaterials()
        {
            if (!Context.Materials.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedMaterialTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedMaterials(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedTechnologies()
        {
            if (!Context.Technologies.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedTechnologies(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedFixedCosts()
        {
            if (!Context.FixedCosts.Any())
            {
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCostCategories(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCostTypes(Context);
                SeedDatabase.Seeds.SeedDatabase.SeedFixedCosts(Context);
            }
            return RedirectToAction("Index", "Home", null);
        }

        public ActionResult SeedTest()
        {
            RecreateDatabase();
            SeedDatabase.Seeds.SeedDatabase.AddUsersAndRoles(Context);
            SeedDatabase.Seeds.SeedDatabase.SeedTestInstance(Context);

            var user = Context.Users.First();

            foreach(var order in Context.Orders.ToList())
            {
                OrderEditHelper.AutorizeOrder(order, user, Context);
                OrderDatabaseHelper.IntoProduction(order, user, Context);
            }

            return RedirectToAction("Index", "Home", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Batat/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Batat/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Batat/Views/Home/Index.cshtml
<!DOCTYPE html>
<html class="html-base" lang="@System.Globalization.CultureInfo.CurrentUICulture.Name" style="overflow-y: hidden !important; overflow-x: hidden !important;">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    <!-- Please Wait scripts and CSS -->
    <script type="text/javascript" src="~/3rdParty/PleaseWait/PleaseWait.js"></script>
    <link rel="stylesheet" href="~/3rdParty/PleaseWait/PleaseWait.css" />
    <link rel="stylesheet" href="~/3rdParty/PleaseWait/LoadingCircles.css" />
    <!--  END -->
    <!-- STOP CACHING DATA! -->
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <!--END-->
    <!--END-->
    <!-- Third Party -->
    <!-- jQuery -->
    <script src="~/3rdParty/jQuery/2.2.4/jQuery.min.js" type="text/javascript"></script>

    <!-- moment -->
    <script src="~/3rdParty/moment/2.7.0/moment.min.js" type="text/javascript"></script>

    <!-- Bootstrap -->
    <script type="text/javascript" src="~/3rdParty/tether/1.4.0/tether.min.js"></script>
    <script type="text/javascript" src="~/3rdParty/bootstrap/3.3.7/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/3rdParty/respond.js/1.1.0/respond.min.js"></script>
    <link rel="stylesheet" href="~/3rdParty/bootstrap/3.3.7/bootstrap.min.css" />

    <!-- Load angular root files -->
    <link href="~/3rdParty/ui-datepicker/datepicker.css" rel="stylesheet" />
    <link href="~/3rdParty/ui-datepicker/base.css" rel="stylesheet" />

    <script type="text/javascript" src="~/batat/batat.start.js?<%=@DateTime.Now.Ticks.ToString()%>"></script>
    <script type="text/javascript" src="~/startPage/startPage.start.js?<%=@DateTime.Now.Ticks.ToString()%>"></script>
    <script type="text/javascript" src="~/batat/Directives/directives.js?<%=@DateTime.Now.Ticks.ToString()%>"></script>

    <!--END-->
    <link rel="stylesheet" href="~/Content/HomeScreen.css?<%=@DateTime.Now.Ticks.ToString()%>" />
    <link rel="stylesheet" href="~/Content/Site.css?<%=@DateTime.Now.Ticks.ToString()%>" />

</head>


<body id="body" class="body-base" layout="column"
      ng-app="startPage">

    <script type="text/javascript">
        window.myPleaseWait = function (message) {
            return window.pleaseWait({
                logo: [],
                backgroundColor: '#EAE8E1',
                loadingHtml: "<p class='loading-message'>" + message + "</p><div class='sk-fading-circle'><div class='sk-circle1 sk-circle'></div>" +
                            "<div class='sk-circle2 sk-circle'></div><div class='sk-circle3 sk-circle'></div><div class='sk-circle4 sk-circle'></div><div class='sk-circle5 sk-circle'></div>" +
                            "<div class='sk-circle6 sk-circle'></div><div class='sk-circle7 sk-circle'></div><div class='sk-circle8 sk-circle'></div><div class='sk-circle9 sk-circle'></div>" +
                            "<div class='sk-circle10 sk-circle'></div><div class='sk-circle11 sk-circle'></div><div class='sk-circle12 sk-circle'></div></div>"
            });
        }
        window.loading_layout_page_screen = (window.myPleaseWait("Loading layout page and scripts"));
    </script>

    

    <div class="my-navbar-inverse navbar navbar-inverse navbar-fixed-top navbar-shared-top">
        <div class="container-fluid center-content-both" id="navbar-container-div">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Administrator<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href='@Url.Action("RecreateDatabase", "SeedDatabase")'>Recreate database</a></li>
                            <li><a href='@Url.Action("SeedDatabasePanel", "SeedDatabase")'>Seed PA</a></li>
                            <li><a href='@Url.Action("SeedOrders", "SeedDatabase")'>Seed Orders</a></li>
                            <li><a href='@Url.Action("SeedOrderInstances", "SeedDatabase")'>Move Orders to production panel</a></li>
                            <li><a href='@Url.Action("SeedTechnologyPicks", "SeedDatabase")'>Seed Technology picks</a></li>
                            <li><a href='@Url.Action("SeedTroleys", "SeedDatabase")'>Seed Troleys</a></li>
                            <li><a href='@Url.Action("RemoveOrderInstances", "SeedDatabase")'>Remove Orders in production</a></li>
                            <li><a href='@Url.Action("SeedTest", "SeedDatabase")'>Seed test</a></li>
                            <!--
    <li><a href='@Url.Action("ReseedOiOnly", "SeedDatabase")'>Reseed Boxes Only</a></li>
    <li><a href='@Url.Action("SeedOrders", "SeedDatabase")'>Seed Orders</a></li>
    <li><a href='@Url.Action("SeedProducts", "SeedDatabase")'>Seed Products</a></li>
    <li><a href='@Url.Action("SeedParts", "SeedDatabase")'>Seed Parts</a></li>
    <li><a href='@Url.Action("SeedParameters", "SeedDatabase")'>Seed Parameters</a></li>
    <li><a href='@Url.Action("SeedGroups", "SeedDatabase")'>Seed Groups</a></li>
    <li><a href='@Url.Action("SeedSubjects", "SeedDatabase")'>Seed Subjects and Contacts</a></li>
    <li><a href='@Url.Action("SeedTechnologies", "SeedDatabase")'>Seed Technologies and Operations</a></li>
    <li><a href='@Url.Action("SeedOperators", "SeedDatabase")'>Seed Operators</a></li>
    <li><a href='@Url.Action("SeedMachines", "SeedDatabase")'>Seed Machines</a></li>
    <li><a href='@Url.Action("SeedTools", "SeedDatabase")'>Seed Tools</a></li>
    <li><a href='@Url.Action("SeedMaterials", "SeedDatabase")'>Seed Materials</a></li>
    <li><a href='@Url.Action("SeedFixedCosts", "SeedDatabase")'>Seed FixedCosts</a></li>
    -->
                        </ul>
                    </li>
                </ul>
            </div>
            <a class="btn btn-default" href="/SmartAdmin/WikiPanel.html">Wiki</a>
            @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
        </div>
    </div>

    <div class="home-screen-body">
        <div class="container-fluid home-screen-tiles-container">
            <div class="row-fluid home-screen-tiles-row">

                <div class="col-sm-6 home-screen-tile" title="Panel Danych">
                    <div class="center-content-both">
                        <div class="home-screen-link home-screen-link-database-panel">
                            <a href="/SmartAdmin/DatabasePanel.html" class="stretch-absolute"></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 home-screen-tile" title="Panel Operatora">
                    <div class="center-content-both">
                        <div class="home-screen-link home-screen-link-operator-panel">
                            <a href="/SmartAdmin/OperatorPanel.html" class="stretch-absolute"></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 home-screen-tile"  title="Panel Produkcji">
                    <div class="center-content-both">
                        <div class="home-screen-link home-screen-link-production-panel">
                            <a href="/ProductionPanel/" class="stretch-absolute"></a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 home-screen-tile"  title="Panel Statystyk">
                    <div class="center-content-both">
                        <div class="home-screen-link home-screen-link-statistics-panel">
                            <a href="/SmartAdmin/TilesPanel.html" class="stretch-absolute"></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    
    
</body>


</html>

<script>
    window.loading_layout_page_screen.finish();
</script>